openapi: 3.0.0
info:
  title: Media Downloader API
  description: API for downloading videos from YouTube, TikTok, and more
  version: 1.0.0
servers:
  - url: https://media-downloader-api-45bf.onrender.com/api/v1
paths:
  /status:
    get:
      summary: Get API status
      responses:
        200:
          description: OK
  /download/facebook:
    post:
      summary: Download a Facebook video
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
      responses:
        200:
          description: OK
  /download/tiktok:
    post:
      summary: Download a TikTok video
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
      responses:
        200:
          description: OK
  /download/instagram:
    post:
      summary: Download an Instagram video
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
      responses:
        200:
          description: OK
  /download/youtube:
    post:
      summary: Download a YouTube video
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
      responses:
        200:
          description: OK 
  /download/twitter:
    post:
      summary: Download a Twitter video
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
      responses:
        200:
          description: OK   
  /download/all:
    post:
      summary: Download a video from various platforms like YouTube, Instagram, etc.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
      responses:
        200:
          description: OK
        
